# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables: 
- template: variables.yml

stages:
- template: stages/ci.yml
- template: stages/cd.yml